export const genders = [
  'Ação',
  'Aventura',
  'Cinema de arte',
  'Chanchada',
  'Comédia',
  'Comédia romântica',
  'Comédia dramática',
  'Comédia de ação',
  'Dança',
  'Documentário',
  'Docuficção',
  'Drama',
  'Espionagem',
  'Escolar',
  'Faroeste',
  'Fantasia científica',
  'Ficção científica',
  'Filmes de guerra',
  'Fantasia',
  'Guerra',
  'Musical',
  'Filme policial',
  'Romance',
  'Seriado',
  'Suspense',
  'Terror'
];
